name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install OS dependencies
      run: apt-get update -y && apt-get install -y p7zip-full
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Build release
      run: crystal build src/dynodocker.cr --release
    # - name: Create dynodocker archive
    #   shell: bash
    #   env:
    #     ZIP_NAME: dynodocker-linux
    #   run: |
    #     mkdir artifact
    #     7z a artifact/${ZIP_NAME}.zip $(find . -name dynodocker)
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dynodocker-linux
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}