name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install OS dependencies
      run: apt-get update -y && apt-get install -y p7zip-full
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Build release
      run: crystal build src/dynodocker.cr --release
    - name: Create archive
      shell: bash
      env:
        ZIP_NAME: dynodocker
      run: |
        mkdir artifact
        mv dynodocker artifact/
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dynodocker
        path: artifact
    - name: Upload binaries to release
      uses: ncipollo/release-action@v1
      with:
        name: dynodocker-latest
        artifacts: "artifact/dynodocker"
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

